admin_id: 627585966
http_port: 8071
websocket_url: ws://10.0.0.101:13001
websocket_token: '1'
file_dir: ./pdf/
log_dir: ./logs
remote_user: zuichen
remote_host: 10.0.0.101
remote_temp_dir: /home/zuichen/Server/Napcat2/.config/QQ/temp/
local_ssh_key: /home/zuichen/.ssh/id_rsa
docker_internal_path: /app/.config/QQ/temp/
max_concurrent_downloads: 2
max_episodes: 20
send_mode_global: pdf
send_mode_group:
    '609976107': pdf
    '992833511': zip
enc_enabled_global: false
enc_enabled_group:
    '609976107': true
    '992833511': true
    '838187768': true
    '741048265': true
    '707971900': true
enc_password_global: ''
enc_password_group:
    '609976107': '123456'
    '992833511': '321'
    '838187768': '350234'
    '741048265': '123456'
    '707971900': '114514'
regex_enabled_global: false
regex_enabled_group:
    '741048265': true
    '838187768': true
    '707971900': true
    '992833511': true
banned_id: []
banned_user: []
banned_group: []
banned_tags: []
random_password_enabled_group:
    '609976107': true
    '992833511': true
send_name_mode_group:
    '609976107': jm
